// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Argocd = Pulumi.Argocd;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var @private = new Argocd.RepositoryCredentials("private", new()
    ///     {
    ///         SshPrivateKey = @"-----BEGIN OPENSSH PRIVATE KEY-----
    /// foo
    /// bar
    /// -----END OPENSSH PRIVATE KEY-----
    /// ",
    ///         Url = "git@private-git-repository.local",
    ///         Username = "git",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Repository credentials can be imported using the repository URL.
    /// 
    ///  Note: as the ArgoCD API does not return any sensitive information, a
    /// 
    ///  subsequent `pulumi up` should be executed to make the `password`,
    /// 
    ///  `ssh_private_key` and `tls_client_cert_key` attributes converge to their
    /// 
    ///  expected values defined within the plan.
    /// 
    ///  Example:
    /// 
    /// ```sh
    /// $ pulumi import argocd:index/repositoryCredentials:RepositoryCredentials myrepocreds git@private-git-repository.local:somerepo.git
    /// ```
    /// </summary>
    [ArgocdResourceType("argocd:index/repositoryCredentials:RepositoryCredentials")]
    public partial class RepositoryCredentials : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether `helm-oci` support should be enabled for this repo.
        /// </summary>
        [Output("enableOci")]
        public Output<bool?> EnableOci { get; private set; } = null!;

        /// <summary>
        /// GitHub API URL for GitHub app authentication.
        /// </summary>
        [Output("githubappEnterpriseBaseUrl")]
        public Output<string?> GithubappEnterpriseBaseUrl { get; private set; } = null!;

        /// <summary>
        /// Github App ID of the app used to access the repo for GitHub app authentication.
        /// </summary>
        [Output("githubappId")]
        public Output<string?> GithubappId { get; private set; } = null!;

        /// <summary>
        /// ID of the installed GitHub App for GitHub app authentication.
        /// </summary>
        [Output("githubappInstallationId")]
        public Output<string?> GithubappInstallationId { get; private set; } = null!;

        /// <summary>
        /// Private key data (PEM) for authentication via GitHub app.
        /// </summary>
        [Output("githubappPrivateKey")]
        public Output<string?> GithubappPrivateKey { get; private set; } = null!;

        /// <summary>
        /// Password for authenticating at the repo server.
        /// </summary>
        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        /// <summary>
        /// Private key data for authenticating at the repo server using SSH (only Git repos).
        /// </summary>
        [Output("sshPrivateKey")]
        public Output<string?> SshPrivateKey { get; private set; } = null!;

        /// <summary>
        /// TLS client cert data for authenticating at the repo server.
        /// </summary>
        [Output("tlsClientCertData")]
        public Output<string?> TlsClientCertData { get; private set; } = null!;

        /// <summary>
        /// TLS client cert key for authenticating at the repo server.
        /// </summary>
        [Output("tlsClientCertKey")]
        public Output<string?> TlsClientCertKey { get; private set; } = null!;

        /// <summary>
        /// URL that these credentials matches to.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;

        /// <summary>
        /// Username for authenticating at the repo server.
        /// </summary>
        [Output("username")]
        public Output<string?> Username { get; private set; } = null!;


        /// <summary>
        /// Create a RepositoryCredentials resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RepositoryCredentials(string name, RepositoryCredentialsArgs args, CustomResourceOptions? options = null)
            : base("argocd:index/repositoryCredentials:RepositoryCredentials", name, args ?? new RepositoryCredentialsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RepositoryCredentials(string name, Input<string> id, RepositoryCredentialsState? state = null, CustomResourceOptions? options = null)
            : base("argocd:index/repositoryCredentials:RepositoryCredentials", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "githubappPrivateKey",
                    "password",
                    "sshPrivateKey",
                    "tlsClientCertKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RepositoryCredentials resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RepositoryCredentials Get(string name, Input<string> id, RepositoryCredentialsState? state = null, CustomResourceOptions? options = null)
        {
            return new RepositoryCredentials(name, id, state, options);
        }
    }

    public sealed class RepositoryCredentialsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether `helm-oci` support should be enabled for this repo.
        /// </summary>
        [Input("enableOci")]
        public Input<bool>? EnableOci { get; set; }

        /// <summary>
        /// GitHub API URL for GitHub app authentication.
        /// </summary>
        [Input("githubappEnterpriseBaseUrl")]
        public Input<string>? GithubappEnterpriseBaseUrl { get; set; }

        /// <summary>
        /// Github App ID of the app used to access the repo for GitHub app authentication.
        /// </summary>
        [Input("githubappId")]
        public Input<string>? GithubappId { get; set; }

        /// <summary>
        /// ID of the installed GitHub App for GitHub app authentication.
        /// </summary>
        [Input("githubappInstallationId")]
        public Input<string>? GithubappInstallationId { get; set; }

        [Input("githubappPrivateKey")]
        private Input<string>? _githubappPrivateKey;

        /// <summary>
        /// Private key data (PEM) for authentication via GitHub app.
        /// </summary>
        public Input<string>? GithubappPrivateKey
        {
            get => _githubappPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _githubappPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Password for authenticating at the repo server.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("sshPrivateKey")]
        private Input<string>? _sshPrivateKey;

        /// <summary>
        /// Private key data for authenticating at the repo server using SSH (only Git repos).
        /// </summary>
        public Input<string>? SshPrivateKey
        {
            get => _sshPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _sshPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// TLS client cert data for authenticating at the repo server.
        /// </summary>
        [Input("tlsClientCertData")]
        public Input<string>? TlsClientCertData { get; set; }

        [Input("tlsClientCertKey")]
        private Input<string>? _tlsClientCertKey;

        /// <summary>
        /// TLS client cert key for authenticating at the repo server.
        /// </summary>
        public Input<string>? TlsClientCertKey
        {
            get => _tlsClientCertKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _tlsClientCertKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// URL that these credentials matches to.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        /// <summary>
        /// Username for authenticating at the repo server.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public RepositoryCredentialsArgs()
        {
        }
        public static new RepositoryCredentialsArgs Empty => new RepositoryCredentialsArgs();
    }

    public sealed class RepositoryCredentialsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether `helm-oci` support should be enabled for this repo.
        /// </summary>
        [Input("enableOci")]
        public Input<bool>? EnableOci { get; set; }

        /// <summary>
        /// GitHub API URL for GitHub app authentication.
        /// </summary>
        [Input("githubappEnterpriseBaseUrl")]
        public Input<string>? GithubappEnterpriseBaseUrl { get; set; }

        /// <summary>
        /// Github App ID of the app used to access the repo for GitHub app authentication.
        /// </summary>
        [Input("githubappId")]
        public Input<string>? GithubappId { get; set; }

        /// <summary>
        /// ID of the installed GitHub App for GitHub app authentication.
        /// </summary>
        [Input("githubappInstallationId")]
        public Input<string>? GithubappInstallationId { get; set; }

        [Input("githubappPrivateKey")]
        private Input<string>? _githubappPrivateKey;

        /// <summary>
        /// Private key data (PEM) for authentication via GitHub app.
        /// </summary>
        public Input<string>? GithubappPrivateKey
        {
            get => _githubappPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _githubappPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Password for authenticating at the repo server.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("sshPrivateKey")]
        private Input<string>? _sshPrivateKey;

        /// <summary>
        /// Private key data for authenticating at the repo server using SSH (only Git repos).
        /// </summary>
        public Input<string>? SshPrivateKey
        {
            get => _sshPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _sshPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// TLS client cert data for authenticating at the repo server.
        /// </summary>
        [Input("tlsClientCertData")]
        public Input<string>? TlsClientCertData { get; set; }

        [Input("tlsClientCertKey")]
        private Input<string>? _tlsClientCertKey;

        /// <summary>
        /// TLS client cert key for authenticating at the repo server.
        /// </summary>
        public Input<string>? TlsClientCertKey
        {
            get => _tlsClientCertKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _tlsClientCertKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// URL that these credentials matches to.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        /// <summary>
        /// Username for authenticating at the repo server.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public RepositoryCredentialsState()
        {
        }
        public static new RepositoryCredentialsState Empty => new RepositoryCredentialsState();
    }
}
