// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMergeTemplateSpecSyncPolicy
    {
        /// <summary>
        /// Whether to automatically keep an application synced to the target revision.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeTemplateSpecSyncPolicyAutomated? Automated;
        /// <summary>
        /// Controls metadata in the given namespace (if `CreateNamespace=true`).
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeTemplateSpecSyncPolicyManagedNamespaceMetadata? ManagedNamespaceMetadata;
        /// <summary>
        /// Controls failed sync retry behavior.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeTemplateSpecSyncPolicyRetry? Retry;
        /// <summary>
        /// List of sync options. More info: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/.
        /// </summary>
        public readonly ImmutableArray<string> SyncOptions;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMergeGeneratorMergeTemplateSpecSyncPolicy(
            Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeTemplateSpecSyncPolicyAutomated? automated,

            Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeTemplateSpecSyncPolicyManagedNamespaceMetadata? managedNamespaceMetadata,

            Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeTemplateSpecSyncPolicyRetry? retry,

            ImmutableArray<string> syncOptions)
        {
            Automated = automated;
            ManagedNamespaceMetadata = managedNamespaceMetadata;
            Retry = retry;
            SyncOptions = syncOptions;
        }
    }
}
