// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorListTemplateSpecSourcePlugin
    {
        /// <summary>
        /// Environment variables passed to the plugin.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorListTemplateSpecSourcePluginEnv> Envs;
        /// <summary>
        /// Name of the applicationsets.argoproj.io, must be unique. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorListTemplateSpecSourcePlugin(
            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorListTemplateSpecSourcePluginEnv> envs,

            string? name)
        {
            Envs = envs;
            Name = name;
        }
    }
}
