// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorMergeGenerator
    {
        /// <summary>
        /// The [cluster decision resource](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster-Decision-Resource/) generates a list of Argo CD clusters.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorClusterDecisionResource> ClusterDecisionResources;
        /// <summary>
        /// The [cluster generator](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster/) produces parameters based on the list of items found within the cluster secret.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorCluster> Clusters;
        /// <summary>
        /// [Git generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/) generates parameters using either the directory structure of a specified Git repository (directory generator), or, using the contents of JSON/YAML files found within a specified repository (file generator).
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorGit> Gits;
        /// <summary>
        /// [List generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-List/) generate parameters based on an arbitrary list of key/value pairs (as long as the values are string values).
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorList> Lists;
        /// <summary>
        /// [Pull Request generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/) uses the API of an SCMaaS provider to automatically discover open pull requests within a repository.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorPullRequest> PullRequests;
        /// <summary>
        /// [SCM Provider generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/) uses the API of an SCMaaS provider to automatically discover repositories within an organization.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorScmProvider> ScmProviders;
        /// <summary>
        /// Label selector used to narrow the scope of targeted clusters.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorSelector? Selector;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMatrixGeneratorMergeGenerator(
            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorClusterDecisionResource> clusterDecisionResources,

            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorCluster> clusters,

            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorGit> gits,

            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorList> lists,

            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorPullRequest> pullRequests,

            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorScmProvider> scmProviders,

            Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorSelector? selector)
        {
            ClusterDecisionResources = clusterDecisionResources;
            Clusters = clusters;
            Gits = gits;
            Lists = lists;
            PullRequests = pullRequests;
            ScmProviders = scmProviders;
            Selector = selector;
        }
    }
}
