// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationStatus
    {
        /// <summary>
        /// List of currently observed application conditions.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationStatusCondition> Conditions;
        /// <summary>
        /// Application's current health status.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationStatusHealth> Healths;
        /// <summary>
        /// Information about any ongoing operations, such as a sync.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationStatusOperationState> OperationStates;
        /// <summary>
        /// When the application state was reconciled using the latest git version.
        /// </summary>
        public readonly string? ReconciledAt;
        /// <summary>
        /// List of Kubernetes resources managed by this application.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationStatusResource> Resources;
        /// <summary>
        /// List of URLs and container images used by this application.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationStatusSummary> Summaries;
        /// <summary>
        /// Application's current sync status
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationStatusSync> Syncs;

        [OutputConstructor]
        private ApplicationStatus(
            ImmutableArray<Outputs.ApplicationStatusCondition> conditions,

            ImmutableArray<Outputs.ApplicationStatusHealth> healths,

            ImmutableArray<Outputs.ApplicationStatusOperationState> operationStates,

            string? reconciledAt,

            ImmutableArray<Outputs.ApplicationStatusResource> resources,

            ImmutableArray<Outputs.ApplicationStatusSummary> summaries,

            ImmutableArray<Outputs.ApplicationStatusSync> syncs)
        {
            Conditions = conditions;
            Healths = healths;
            OperationStates = operationStates;
            ReconciledAt = reconciledAt;
            Resources = resources;
            Summaries = summaries;
            Syncs = syncs;
        }
    }
}
