// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMerge
    {
        /// <summary>
        /// Application set generators. Generators are responsible for generating parameters, which are then rendered into the template: fields of the ApplicationSet resource.
        /// </summary>
        public readonly ImmutableArray<Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGenerator> Generators;
        /// <summary>
        /// Keys to merge into resulting parameter set.
        /// </summary>
        public readonly ImmutableArray<string> MergeKeys;
        /// <summary>
        /// Generator template. Used to override the values of the spec-level template.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeTemplate? Template;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMergeGeneratorMerge(
            ImmutableArray<Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGenerator> generators,

            ImmutableArray<string> mergeKeys,

            Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeTemplate? template)
        {
            Generators = generators;
            MergeKeys = mergeKeys;
            Template = template;
        }
    }
}
