// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorScmProviderGitlab
    {
        /// <summary>
        /// Scan all branches instead of just the default branch.
        /// </summary>
        public readonly bool? AllBranches;
        /// <summary>
        /// The Bitbucket REST API URL to talk to e.g. https://bitbucket.org/rest.
        /// </summary>
        public readonly string? Api;
        /// <summary>
        /// The Kubernetes resource Group to match for.
        /// </summary>
        public readonly string Group;
        /// <summary>
        /// Recurse through subgroups (true) or scan only the base group (false). Defaults to `false`.
        /// </summary>
        public readonly bool? IncludeSubgroups;
        /// <summary>
        /// Authentication token reference.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorScmProviderGitlabTokenRef? TokenRef;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorScmProviderGitlab(
            bool? allBranches,

            string? api,

            string group,

            bool? includeSubgroups,

            Outputs.ApplicationSetSpecGeneratorScmProviderGitlabTokenRef? tokenRef)
        {
            AllBranches = allBranches;
            Api = api;
            Group = group;
            IncludeSubgroups = includeSubgroups;
            TokenRef = tokenRef;
        }
    }
}
