// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorList
    {
        /// <summary>
        /// List of key/value pairs to pass as parameters into the template
        /// </summary>
        public readonly ImmutableArray<ImmutableDictionary<string, string>> Elements;
        /// <summary>
        /// Generator template. Used to override the values of the spec-level template.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorListTemplate? Template;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorList(
            ImmutableArray<ImmutableDictionary<string, string>> elements,

            Outputs.ApplicationSetSpecGeneratorListTemplate? template)
        {
            Elements = elements;
            Template = template;
        }
    }
}
