// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ClusterConfig
    {
        public readonly ImmutableArray<Outputs.ClusterConfigAwsAuthConfig> AwsAuthConfigs;
        /// <summary>
        /// Server requires Bearer authentication. The client will not attempt to use refresh tokens for an OAuth2 flow.
        /// </summary>
        public readonly string? BearerToken;
        /// <summary>
        /// Configuration for an exec provider used to call an external command to perform cluster authentication See: https://godoc.org/k8s.io/client-go/tools/clientcmd/api#ExecConfig.
        /// </summary>
        public readonly Outputs.ClusterConfigExecProviderConfig? ExecProviderConfig;
        /// <summary>
        /// Password for servers that require Basic authentication.
        /// </summary>
        public readonly string? Password;
        /// <summary>
        /// Settings to enable transport layer security when connecting to the cluster.
        /// </summary>
        public readonly Outputs.ClusterConfigTlsClientConfig? TlsClientConfig;
        /// <summary>
        /// Username for servers that require Basic authentication.
        /// </summary>
        public readonly string? Username;

        [OutputConstructor]
        private ClusterConfig(
            ImmutableArray<Outputs.ClusterConfigAwsAuthConfig> awsAuthConfigs,

            string? bearerToken,

            Outputs.ClusterConfigExecProviderConfig? execProviderConfig,

            string? password,

            Outputs.ClusterConfigTlsClientConfig? tlsClientConfig,

            string? username)
        {
            AwsAuthConfigs = awsAuthConfigs;
            BearerToken = bearerToken;
            ExecProviderConfig = execProviderConfig;
            Password = password;
            TlsClientConfig = tlsClientConfig;
            Username = username;
        }
    }
}
