// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ClusterConfigAwsAuthConfig
    {
        /// <summary>
        /// AWS cluster name.
        /// </summary>
        public readonly string? ClusterName;
        /// <summary>
        /// IAM role ARN. If set then AWS IAM Authenticator assume a role to perform cluster operations instead of the default AWS credential provider chain.
        /// </summary>
        public readonly string? RoleArn;

        [OutputConstructor]
        private ClusterConfigAwsAuthConfig(
            string? clusterName,

            string? roleArn)
        {
            ClusterName = clusterName;
            RoleArn = roleArn;
        }
    }
}
