// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ProjectSpecRole
    {
        /// <summary>
        /// Project description.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// List of OIDC group claims bound to this role.
        /// </summary>
        public readonly ImmutableArray<string> Groups;
        /// <summary>
        /// Name of the appprojects.argoproj.io, must be unique. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// List of casbin formatted strings that define access policies for the role in the project. For more information, see the [ArgoCD RBAC reference](https://argoproj.github.io/argo-cd/operator-manual/rbac/#rbac-permission-structure).
        /// </summary>
        public readonly ImmutableArray<string> Policies;

        [OutputConstructor]
        private ProjectSpecRole(
            string? description,

            ImmutableArray<string> groups,

            string name,

            ImmutableArray<string> policies)
        {
            Description = description;
            Groups = groups;
            Name = name;
            Policies = policies;
        }
    }
}
