// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ProjectSpecOrphanedResources
    {
        public readonly ImmutableArray<Outputs.ProjectSpecOrphanedResourcesIgnore> Ignores;
        /// <summary>
        /// Whether a warning condition should be created for apps which have orphaned resources.
        /// </summary>
        public readonly bool? Warn;

        [OutputConstructor]
        private ProjectSpecOrphanedResources(
            ImmutableArray<Outputs.ProjectSpecOrphanedResourcesIgnore> ignores,

            bool? warn)
        {
            Ignores = ignores;
            Warn = warn;
        }
    }
}
