// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package argocd

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-argocd/sdk/go/argocd/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "argocd:index/accountToken:AccountToken":
		r = &AccountToken{}
	case "argocd:index/application:Application":
		r = &Application{}
	case "argocd:index/applicationSet:ApplicationSet":
		r = &ApplicationSet{}
	case "argocd:index/cluster:Cluster":
		r = &Cluster{}
	case "argocd:index/project:Project":
		r = &Project{}
	case "argocd:index/projectToken:ProjectToken":
		r = &ProjectToken{}
	case "argocd:index/repository:Repository":
		r = &Repository{}
	case "argocd:index/repositoryCertificate:RepositoryCertificate":
		r = &RepositoryCertificate{}
	case "argocd:index/repositoryCredentials:RepositoryCredentials":
		r = &RepositoryCredentials{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:argocd" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"argocd",
		"index/accountToken",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"argocd",
		"index/application",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"argocd",
		"index/applicationSet",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"argocd",
		"index/cluster",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"argocd",
		"index/project",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"argocd",
		"index/projectToken",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"argocd",
		"index/repository",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"argocd",
		"index/repositoryCertificate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"argocd",
		"index/repositoryCredentials",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"argocd",
		&pkg{version},
	)
}
