// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorPullRequestGitlabArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Bitbucket REST API URL to talk to e.g. https://bitbucket.org/rest.
        /// </summary>
        [Input("api")]
        public Input<string>? Api { get; set; }

        [Input("labels")]
        private InputList<string>? _labels;

        /// <summary>
        /// Map of string keys and values that can be used to organize and categorize (scope and select) the applicationsets.argoproj.io. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels
        /// </summary>
        public InputList<string> Labels
        {
            get => _labels ?? (_labels = new InputList<string>());
            set => _labels = value;
        }

        /// <summary>
        /// The project the application belongs to. Defaults to `default`.
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        /// <summary>
        /// additional MRs filter to get only those with a certain state. Default:  "" (all states).
        /// </summary>
        [Input("pullRequestState")]
        public Input<string>? PullRequestState { get; set; }

        /// <summary>
        /// Authentication token reference.
        /// </summary>
        [Input("tokenRef")]
        public Input<Inputs.ApplicationSetSpecGeneratorPullRequestGitlabTokenRefArgs>? TokenRef { get; set; }

        public ApplicationSetSpecGeneratorPullRequestGitlabArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorPullRequestGitlabArgs Empty => new ApplicationSetSpecGeneratorPullRequestGitlabArgs();
    }
}
