// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationStatusOperationStateGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Time of operation completion.
        /// </summary>
        [Input("finishedAt")]
        public Input<string>? FinishedAt { get; set; }

        /// <summary>
        /// Any pertinent messages when attempting to perform operation (typically errors).
        /// </summary>
        [Input("message")]
        public Input<string>? Message { get; set; }

        /// <summary>
        /// The current phase of the operation.
        /// </summary>
        [Input("phase")]
        public Input<string>? Phase { get; set; }

        /// <summary>
        /// Count of operation retries.
        /// </summary>
        [Input("retryCount")]
        public Input<string>? RetryCount { get; set; }

        /// <summary>
        /// Time of operation start.
        /// </summary>
        [Input("startedAt")]
        public Input<string>? StartedAt { get; set; }

        public ApplicationStatusOperationStateGetArgs()
        {
        }
        public static new ApplicationStatusOperationStateGetArgs Empty => new ApplicationStatusOperationStateGetArgs();
    }
}
