// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorPullRequestGiteaArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Bitbucket REST API URL to talk to e.g. https://bitbucket.org/rest.
        /// </summary>
        [Input("api", required: true)]
        public Input<string> Api { get; set; } = null!;

        /// <summary>
        /// Allow insecure tls, for self-signed certificates; default: false.
        /// </summary>
        [Input("insecure")]
        public Input<bool>? Insecure { get; set; }

        /// <summary>
        /// Gitea org or user to scan.
        /// </summary>
        [Input("owner", required: true)]
        public Input<string> Owner { get; set; } = null!;

        /// <summary>
        /// Repo name to scan.
        /// </summary>
        [Input("repo", required: true)]
        public Input<string> Repo { get; set; } = null!;

        /// <summary>
        /// Authentication token reference.
        /// </summary>
        [Input("tokenRef")]
        public Input<Inputs.ApplicationSetSpecGeneratorMatrixGeneratorPullRequestGiteaTokenRefArgs>? TokenRef { get; set; }

        public ApplicationSetSpecGeneratorMatrixGeneratorPullRequestGiteaArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMatrixGeneratorPullRequestGiteaArgs Empty => new ApplicationSetSpecGeneratorMatrixGeneratorPullRequestGiteaArgs();
    }
}
