// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMatrixArgs : global::Pulumi.ResourceArgs
    {
        [Input("generators", required: true)]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorArgs>? _generators;

        /// <summary>
        /// Application set generators. Generators are responsible for generating parameters, which are then rendered into the template: fields of the ApplicationSet resource.
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorArgs> Generators
        {
            get => _generators ?? (_generators = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorArgs>());
            set => _generators = value;
        }

        /// <summary>
        /// Generator template. Used to override the values of the spec-level template.
        /// </summary>
        [Input("template")]
        public Input<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixTemplateArgs>? Template { get; set; }

        public ApplicationSetSpecGeneratorMergeGeneratorMatrixArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMatrixArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMatrixArgs();
    }
}
