// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestTemplateSpecIgnoreDifferenceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Kubernetes resource Group to match for.
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        [Input("jqPathExpressions")]
        private InputList<string>? _jqPathExpressions;

        /// <summary>
        /// List of JQ path expression strings targeting the field(s) to ignore.
        /// </summary>
        public InputList<string> JqPathExpressions
        {
            get => _jqPathExpressions ?? (_jqPathExpressions = new InputList<string>());
            set => _jqPathExpressions = value;
        }

        [Input("jsonPointers")]
        private InputList<string>? _jsonPointers;

        /// <summary>
        /// List of JSONPaths strings targeting the field(s) to ignore.
        /// </summary>
        public InputList<string> JsonPointers
        {
            get => _jsonPointers ?? (_jsonPointers = new InputList<string>());
            set => _jsonPointers = value;
        }

        /// <summary>
        /// The Kubernetes resource Kind to match for.
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        /// <summary>
        /// Name of the applicationsets.argoproj.io, must be unique. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Namespace of the applicationsets.argoproj.io, must be unique. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        public ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestTemplateSpecIgnoreDifferenceGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestTemplateSpecIgnoreDifferenceGetArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestTemplateSpecIgnoreDifferenceGetArgs();
    }
}
