// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationStatusSummaryGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("externalUrls")]
        private InputList<object>? _externalUrls;

        /// <summary>
        /// All external URLs of application child resources.
        /// </summary>
        public InputList<object> ExternalUrls
        {
            get => _externalUrls ?? (_externalUrls = new InputList<object>());
            set => _externalUrls = value;
        }

        [Input("images")]
        private InputList<object>? _images;

        /// <summary>
        /// List of Kustomize image override specifications.
        /// </summary>
        public InputList<object> Images
        {
            get => _images ?? (_images = new InputList<object>());
            set => _images = value;
        }

        public ApplicationStatusSummaryGetArgs()
        {
        }
        public static new ApplicationStatusSummaryGetArgs Empty => new ApplicationStatusSummaryGetArgs();
    }
}
