// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorMergeArgs : global::Pulumi.ResourceArgs
    {
        [Input("generators", required: true)]
        private InputList<Inputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorArgs>? _generators;

        /// <summary>
        /// Application set generators. Generators are responsible for generating parameters, which are then rendered into the template: fields of the ApplicationSet resource.
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorArgs> Generators
        {
            get => _generators ?? (_generators = new InputList<Inputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorArgs>());
            set => _generators = value;
        }

        [Input("mergeKeys", required: true)]
        private InputList<string>? _mergeKeys;

        /// <summary>
        /// Keys to merge into resulting parameter set.
        /// </summary>
        public InputList<string> MergeKeys
        {
            get => _mergeKeys ?? (_mergeKeys = new InputList<string>());
            set => _mergeKeys = value;
        }

        /// <summary>
        /// Generator template. Used to override the values of the spec-level template.
        /// </summary>
        [Input("template")]
        public Input<Inputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeTemplateArgs>? Template { get; set; }

        public ApplicationSetSpecGeneratorMatrixGeneratorMergeArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMatrixGeneratorMergeArgs Empty => new ApplicationSetSpecGeneratorMatrixGeneratorMergeArgs();
    }
}
