// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationStatusConditionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The time the condition was last observed.
        /// </summary>
        [Input("lastTransitionTime")]
        public Input<string>? LastTransitionTime { get; set; }

        /// <summary>
        /// Human-readable message indicating details about condition.
        /// </summary>
        [Input("message")]
        public Input<string>? Message { get; set; }

        /// <summary>
        /// Application condition type.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public ApplicationStatusConditionGetArgs()
        {
        }
        public static new ApplicationStatusConditionGetArgs Empty => new ApplicationStatusConditionGetArgs();
    }
}
