// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecTemplateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Kubernetes object metadata for templated Application.
        /// </summary>
        [Input("metadata", required: true)]
        public Input<Inputs.ApplicationSetSpecTemplateMetadataArgs> Metadata { get; set; } = null!;

        /// <summary>
        /// The application specification.
        /// </summary>
        [Input("spec", required: true)]
        public Input<Inputs.ApplicationSetSpecTemplateSpecArgs> Spec { get; set; } = null!;

        public ApplicationSetSpecTemplateArgs()
        {
        }
        public static new ApplicationSetSpecTemplateArgs Empty => new ApplicationSetSpecTemplateArgs();
    }
}
