// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationStatusGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Inputs.ApplicationStatusConditionGetArgs>? _conditions;

        /// <summary>
        /// List of currently observed application conditions.
        /// </summary>
        public InputList<Inputs.ApplicationStatusConditionGetArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.ApplicationStatusConditionGetArgs>());
            set => _conditions = value;
        }

        [Input("healths")]
        private InputList<Inputs.ApplicationStatusHealthGetArgs>? _healths;

        /// <summary>
        /// Application's current health status.
        /// </summary>
        public InputList<Inputs.ApplicationStatusHealthGetArgs> Healths
        {
            get => _healths ?? (_healths = new InputList<Inputs.ApplicationStatusHealthGetArgs>());
            set => _healths = value;
        }

        [Input("operationStates")]
        private InputList<Inputs.ApplicationStatusOperationStateGetArgs>? _operationStates;

        /// <summary>
        /// Information about any ongoing operations, such as a sync.
        /// </summary>
        public InputList<Inputs.ApplicationStatusOperationStateGetArgs> OperationStates
        {
            get => _operationStates ?? (_operationStates = new InputList<Inputs.ApplicationStatusOperationStateGetArgs>());
            set => _operationStates = value;
        }

        /// <summary>
        /// When the application state was reconciled using the latest git version.
        /// </summary>
        [Input("reconciledAt")]
        public Input<string>? ReconciledAt { get; set; }

        [Input("resources")]
        private InputList<Inputs.ApplicationStatusResourceGetArgs>? _resources;

        /// <summary>
        /// List of Kubernetes resources managed by this application.
        /// </summary>
        public InputList<Inputs.ApplicationStatusResourceGetArgs> Resources
        {
            get => _resources ?? (_resources = new InputList<Inputs.ApplicationStatusResourceGetArgs>());
            set => _resources = value;
        }

        [Input("summaries")]
        private InputList<Inputs.ApplicationStatusSummaryGetArgs>? _summaries;

        /// <summary>
        /// List of URLs and container images used by this application.
        /// </summary>
        public InputList<Inputs.ApplicationStatusSummaryGetArgs> Summaries
        {
            get => _summaries ?? (_summaries = new InputList<Inputs.ApplicationStatusSummaryGetArgs>());
            set => _summaries = value;
        }

        [Input("syncs")]
        private InputList<Inputs.ApplicationStatusSyncGetArgs>? _syncs;

        /// <summary>
        /// Application's current sync status
        /// </summary>
        public InputList<Inputs.ApplicationStatusSyncGetArgs> Syncs
        {
            get => _syncs ?? (_syncs = new InputList<Inputs.ApplicationStatusSyncGetArgs>());
            set => _syncs = value;
        }

        public ApplicationStatusGetArgs()
        {
        }
        public static new ApplicationStatusGetArgs Empty => new ApplicationStatusGetArgs();
    }
}
