// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Fetch pull requests from a repo hosted on a Bitbucket Server.
        /// </summary>
        [Input("bitbucketServer")]
        public Input<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestBitbucketServerGetArgs>? BitbucketServer { get; set; }

        [Input("filters")]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestFilterGetArgs>? _filters;

        /// <summary>
        /// Filters allow selecting which pull requests to generate for.
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestFilterGetArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestFilterGetArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// Specify the repository from which to fetch the Gitea Pull requests.
        /// </summary>
        [Input("gitea")]
        public Input<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGiteaGetArgs>? Gitea { get; set; }

        /// <summary>
        /// Specify the repository from which to fetch the GitHub Pull requests.
        /// </summary>
        [Input("github")]
        public Input<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGithubGetArgs>? Github { get; set; }

        /// <summary>
        /// Specify the project from which to fetch the GitLab merge requests.
        /// </summary>
        [Input("gitlab")]
        public Input<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGitlabGetArgs>? Gitlab { get; set; }

        /// <summary>
        /// How often to check for changes (in seconds). Default: 3min.
        /// </summary>
        [Input("requeueAfterSeconds")]
        public Input<string>? RequeueAfterSeconds { get; set; }

        /// <summary>
        /// Generator template. Used to override the values of the spec-level template.
        /// </summary>
        [Input("template")]
        public Input<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestTemplateGetArgs>? Template { get; set; }

        public ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGetArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGetArgs();
    }
}
