// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("clusterDecisionResources")]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorClusterDecisionResourceGetArgs>? _clusterDecisionResources;

        /// <summary>
        /// The [cluster decision resource](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster-Decision-Resource/) generates a list of Argo CD clusters.
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorClusterDecisionResourceGetArgs> ClusterDecisionResources
        {
            get => _clusterDecisionResources ?? (_clusterDecisionResources = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorClusterDecisionResourceGetArgs>());
            set => _clusterDecisionResources = value;
        }

        [Input("clusters")]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorClusterGetArgs>? _clusters;

        /// <summary>
        /// The [cluster generator](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster/) produces parameters based on the list of items found within the cluster secret.
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorClusterGetArgs> Clusters
        {
            get => _clusters ?? (_clusters = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorClusterGetArgs>());
            set => _clusters = value;
        }

        [Input("gits")]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorGitGetArgs>? _gits;

        /// <summary>
        /// [Git generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/) generates parameters using either the directory structure of a specified Git repository (directory generator), or, using the contents of JSON/YAML files found within a specified repository (file generator).
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorGitGetArgs> Gits
        {
            get => _gits ?? (_gits = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorGitGetArgs>());
            set => _gits = value;
        }

        [Input("lists")]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorListGetArgs>? _lists;

        /// <summary>
        /// [List generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-List/) generate parameters based on an arbitrary list of key/value pairs (as long as the values are string values).
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorListGetArgs> Lists
        {
            get => _lists ?? (_lists = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorListGetArgs>());
            set => _lists = value;
        }

        [Input("pullRequests")]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGetArgs>? _pullRequests;

        /// <summary>
        /// [Pull Request generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/) uses the API of an SCMaaS provider to automatically discover open pull requests within a repository.
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGetArgs> PullRequests
        {
            get => _pullRequests ?? (_pullRequests = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGetArgs>());
            set => _pullRequests = value;
        }

        [Input("scmProviders")]
        private InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorScmProviderGetArgs>? _scmProviders;

        /// <summary>
        /// [SCM Provider generators](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/) uses the API of an SCMaaS provider to automatically discover repositories within an organization.
        /// </summary>
        public InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorScmProviderGetArgs> ScmProviders
        {
            get => _scmProviders ?? (_scmProviders = new InputList<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorScmProviderGetArgs>());
            set => _scmProviders = value;
        }

        /// <summary>
        /// Label selector used to narrow the scope of targeted clusters.
        /// </summary>
        [Input("selector")]
        public Input<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorSelectorGetArgs>? Selector { get; set; }

        public ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorGetArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorGetArgs();
    }
}
