// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorScmProviderGiteaArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Scan all branches instead of just the default branch.
        /// </summary>
        [Input("allBranches")]
        public Input<bool>? AllBranches { get; set; }

        /// <summary>
        /// The Bitbucket REST API URL to talk to e.g. https://bitbucket.org/rest.
        /// </summary>
        [Input("api")]
        public Input<string>? Api { get; set; }

        /// <summary>
        /// Allow insecure tls, for self-signed certificates; default: false.
        /// </summary>
        [Input("insecure")]
        public Input<bool>? Insecure { get; set; }

        /// <summary>
        /// Gitea org or user to scan.
        /// </summary>
        [Input("owner", required: true)]
        public Input<string> Owner { get; set; } = null!;

        /// <summary>
        /// Authentication token reference.
        /// </summary>
        [Input("tokenRef")]
        public Input<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorScmProviderGiteaTokenRefArgs>? TokenRef { get; set; }

        public ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorScmProviderGiteaArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorScmProviderGiteaArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorScmProviderGiteaArgs();
    }
}
