// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorScmProviderGithubGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Scan all branches instead of just the default branch.
        /// </summary>
        [Input("allBranches")]
        public Input<bool>? AllBranches { get; set; }

        /// <summary>
        /// The Bitbucket REST API URL to talk to e.g. https://bitbucket.org/rest.
        /// </summary>
        [Input("api")]
        public Input<string>? Api { get; set; }

        /// <summary>
        /// Reference to a GitHub App repo-creds secret with permission to access pull requests.
        /// </summary>
        [Input("appSecretName")]
        public Input<string>? AppSecretName { get; set; }

        /// <summary>
        /// Azure Devops organization. E.g. "my-organization".
        /// </summary>
        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        /// <summary>
        /// Authentication token reference.
        /// </summary>
        [Input("tokenRef")]
        public Input<Inputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorScmProviderGithubTokenRefGetArgs>? TokenRef { get; set; }

        public ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorScmProviderGithubGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorScmProviderGithubGetArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorScmProviderGithubGetArgs();
    }
}
