// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ClusterConfigExecProviderConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Preferred input version of the ExecInfo
        /// </summary>
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("args")]
        private InputList<string>? _args;

        /// <summary>
        /// Arguments to pass to the command when executing it
        /// </summary>
        public InputList<string> Args
        {
            get => _args ?? (_args = new InputList<string>());
            set
            {
                var emptySecret = Output.CreateSecret(ImmutableArray.Create<string>());
                _args = Output.All(value, emptySecret).Apply(v => v[0]);
            }
        }

        /// <summary>
        /// Command to execute
        /// </summary>
        [Input("command")]
        public Input<string>? Command { get; set; }

        [Input("env")]
        private InputMap<string>? _env;

        /// <summary>
        /// Env defines additional environment variables to expose to the process. Passed as a map of strings
        /// </summary>
        public InputMap<string> Env
        {
            get => _env ?? (_env = new InputMap<string>());
            set
            {
                var emptySecret = Output.CreateSecret(ImmutableDictionary.Create<string, string>());
                _env = Output.All(value, emptySecret).Apply(v => v[0]);
            }
        }

        /// <summary>
        /// This text is shown to the user when the executable doesn't seem to be present
        /// </summary>
        [Input("installHint")]
        public Input<string>? InstallHint { get; set; }

        public ClusterConfigExecProviderConfigGetArgs()
        {
        }
        public static new ClusterConfigExecProviderConfigGetArgs Empty => new ClusterConfigExecProviderConfigGetArgs();
    }
}
