// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ProjectSpecOrphanedResourcesGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("ignores")]
        private InputList<Inputs.ProjectSpecOrphanedResourcesIgnoreGetArgs>? _ignores;
        public InputList<Inputs.ProjectSpecOrphanedResourcesIgnoreGetArgs> Ignores
        {
            get => _ignores ?? (_ignores = new InputList<Inputs.ProjectSpecOrphanedResourcesIgnoreGetArgs>());
            set => _ignores = value;
        }

        /// <summary>
        /// Whether a warning condition should be created for apps which have orphaned resources.
        /// </summary>
        [Input("warn")]
        public Input<bool>? Warn { get; set; }

        public ProjectSpecOrphanedResourcesGetArgs()
        {
        }
        public static new ProjectSpecOrphanedResourcesGetArgs Empty => new ProjectSpecOrphanedResourcesGetArgs();
    }
}
