// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ProjectSpecDestinationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the appprojects.argoproj.io, must be unique. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Namespace of the appprojects.argoproj.io, must be unique. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
        /// </summary>
        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        /// <summary>
        /// URL of the target cluster and must be set to the Kubernetes control plane API.
        /// </summary>
        [Input("server")]
        public Input<string>? Server { get; set; }

        public ProjectSpecDestinationArgs()
        {
        }
        public static new ProjectSpecDestinationArgs Empty => new ProjectSpecDestinationArgs();
    }
}
